# Generated by Django 4.1.7 on 2023-03-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Enter Your Title', max_length=200, null=True, verbose_name='Post Title'),
        ),
    ]
