# Generated by Django 4.1.7 on 2023-03-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_slug_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('G', 'General'), ('O', 'Ordinary')], default='G', max_length=1),
        ),
    ]
